### ISSUE TITLE
Heroku/Salesforce violation of Acceptable Use and External-Facing Services Policy

### ISSUE THREAD

**Issue by powaqatsi** [viperadnan-git/telegram-message-forwarder-bot#22]
First of all, many thanks for your nice code!

Disclaimer: I'm a newbie with Heroku and Telegram bots.

When I try to deploy the app on Heroku, I get a popup saying that my app cannot be deployed due to a violation of Acceptable Use and External-Facing Services Policy. Has something changed in Salesforce policies or am I doing something wrong?

**Comment by giuseppegg02** [comment]
same error right now, maybe the webserver recognizes some traits in this code and identifies them as incorrect for policy

**Comment by SloboZjalic** [comment]
I think this is a paid app and that's why it gets blocked on heroku.

**Comment by viperadnan-git** [comment]
Heroku is not supported anymore use any other service or vps.
