### ISSUE TITLE
i want to use it for TELEGRAM_SESSION as a user ; but i  open GenString its doesn't work i send screenshot please check it thanks 

### ISSUE THREAD

**Issue by usamariaz2** [viperadnan-git/telegram-message-forwarder-bot#28]
![Screenshot (35)](https://user-images.githubusercontent.com/93404761/177325896-b28b1a4f-b252-45fb-bbf9-3287ca316b5d.png)

**Comment by viperadnan-git** [comment]
Please use the updated code, it has a `gen_session.py` file. Run it to generate session string.
