### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by tarunjangid12** [viperadnan-git/telegram-message-forwarder-bot#37]
Please help me i don't understand what is the actual command to start forwarding 
And please give me example also while giving the solution so i will get exact idea 
![Screenshot_2023-12-23-21-31-14-11_74594bd74a0419242537a8d02ba17993](https://github.com/viperadnan-git/telegram-message-forwarder-bot/assets/146462019/e62499ec-4c51-4fcb-8e39-1623bc5cd6ec)

**Comment by viperadnan-git** [comment]
Channel and Supergroup IDs are in format `-10099998888` where `99998888` is the part from the URL shown in the above screenshot.

**Comment by tarunjangid12** [comment]
Please give me 1 example i didn't get it 
Give me example of command i use 
Like what to use after /forward

**Comment by tarunjangid12** [comment]
I want to know what is chat id and what is first msg id with example

**Comment by viperadnan-git** [comment]
Chat ID is a unique identifier for every chat in Telegram. Every message on Telegram's chat has it's unique ID. The first message ID is the message ID of the first message you want to forward. The forwarding will start from that message and goes until the most recent message in chat. You can learn more about how to get these IDs [here](https://www.alphr.com/find-chat-id-telegram/) or you can just Google it.
