### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by guxuanzhizzzz** [viperadnan-git/telegram-message-forwarder-bot#38]
Hey sir. Is it possible to forward the message to a robot?

**Comment by viperadnan-git** [comment]
yes, when you login as a user

**Comment by guxuanzhizzzz** [comment]
sir login what, could you be more specific? QaQ

**Comment by guxuanzhizzzz** [comment]
I want to forward messages to bots developed by others

**Comment by viperadnan-git** [comment]
Yes you can by setting up bot's chat id in `to` parameter
