### ISSUE TITLE
Can a message from a robot be forwarded to a group?

### ISSUE THREAD

**Issue by winposs** [viperadnan-git/telegram-message-forwarder-bot#43]
I have a telegram robot that will send me messages. 
I want to forward the robot’s messages to the group. 
How should I set it up?
 Thanks

**Comment by viperadnan-git** [comment]
Login as a `User`, using session string. Then setup `from` chat to the
robots chat id and `to` chat to the destination chat.
Note: If you are reading or sending message to a bot then you have to login
as a user, because bots can't interact with each other.

**Comment by WinPoss** [comment]
How can I create api_id and api_hash? I have tried hundreds of times but still get an error message. Is there any way to create telegram’s api_id and api_hash?

**Comment by viperadnan-git** [comment]
From https://my.telegram.org

**Comment by WinPoss** [comment]
> From https://my.telegram.org

I applied through this link, but it kept getting an error message. 
Changing IP and changing browsers couldn't solve it. 
It seems that Google shows that this is a long-standing problem. I'm still looking for a solution.
